version: '3.8'

services:
  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    ports:
      - 5432:5432
    volumes: 
      - ./postgres_data:/var/lib/postgresql
volumes:
  postgresql-volume:
    external: true